# SwiftCompilationError(error: call can throw, but it is not marked with 'try')

let a: A = AImpl()

let result = AKt.foo(a)

exit(result)
